name: ford_ranger
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  ionicons: ^0.2.2
  intl: ^0.18.1
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_ford.png
    - assets/images/drones 1.png
    - assets/images/map.png
    - assets/images/perfil.png
    - assets/images/ranger.png
    - assets/images/Renavam.png
    - assets/images/logo_ford_azul_escuro.png
    - assets/images/ranger_live_kife.png
    - assets/images/back_button.png
    - assets/images/padlock1.png
    - assets/images/bg-home.png
    - assets/images/ranger-sem-fundo.png
    - assets/images/police.png
    - assets/images/radio-icon.png
    - assets/images/alert.png
    - assets/images/cargo-container.png
    - assets/images/info-drone.png
    - assets/images/dots.png
    - assets/images/big-info.png
    - assets/images/breakes.png
    - assets/images/icon-gas.png
    - assets/images/location.png
    - assets/images/map-two-ex.png
    - assets/images/store-front.png
    - assets/images/tools.png
    - assets/images/tools2.png
    - assets/images/Renavam.png
    - assets/images/ranger_picture.png





  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
        - asset: assets/fonts/Inter/Inter-Bold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter/Inter-Light.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter-Thin.ttf
          weight: 700

    - family: PT Sans Caption
      fonts:
        - asset: assets/fonts/PT_Sans_Caption/PTSansCaption-Bold.ttf
        - asset: assets/fonts/PT_Sans_Caption/PTSansCaption-Regular.ttf
          weight: 700
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue/static/Epilogue-Regular.ttf
        - asset: assets/fonts/Epilogue/static/Epilogue-Bold.ttf
          weight: 700